# Analysis options for Smart Ambulance app
# For hackathon demo - suppress deprecation warnings for cleaner output

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false

analyzer:
  errors:
    deprecated_member_use: ignore
